"""Upstream PyTorch control for the sweep.

A WER number on its own cannot tell a port defect from a property of the model or of
the ASR gate. Short utterances score badly in the Core AI sweep — but short clips are
also the hardest case for any ASR, and this checkpoint may simply be weak there. So the
same corpus rows are generated by upstream `TTSModel.generate_audio` (pure PyTorch, the
oracle path) and scored by the identical scorer. The comparison, not the absolute
number, is the port verdict.

Runs in the oracle venv (`.venv`), which has torch 2.13 and no Core AI: nothing here
touches the engine, so there is no IOSurface leak and no worker restarts.

    HF_HOME=$PWD/weights/hf .venv/bin/python conversion/sweep_oracle.py \
        --corpus artifacts/sweep_control_corpus.jsonl --out-dir artifacts/sweep_torch \
        --meta artifacts/sweep_torch_gen.jsonl
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import scipy.io.wavfile
import torch

ROOT = Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default="artifacts/sweep_control_corpus.jsonl")
    ap.add_argument("--out-dir", default="artifacts/sweep_torch")
    ap.add_argument("--meta", default="artifacts/sweep_torch_gen.jsonl")
    ap.add_argument("--seed", type=int, default=1234)
    args = ap.parse_args()

    torch.set_num_threads(1)
    from pocket_tts import TTSModel

    model = TTSModel.load_model().eval()
    rows = [json.loads(l) for l in (ROOT / args.corpus).read_text().splitlines() if l.strip()]
    out_dir = ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    meta_p = ROOT / args.meta
    done = set()
    if meta_p.exists():
        done = {json.loads(l)["id"] for l in meta_p.read_text().splitlines() if l.strip()}
    f = meta_p.open("a")
    states: dict[str, dict] = {}
    t0 = time.monotonic()
    for k, r in enumerate(rows):
        if r["id"] in done:
            continue
        if r["voice"] not in states:
            states[r["voice"]] = model.get_state_for_audio_prompt(r["voice"])
        torch.manual_seed(args.seed)
        t1 = time.monotonic()
        # copy_state=True is upstream's default and is what keeps the voice reusable
        audio = model.generate_audio(states[r["voice"]], r["text"], copy_state=True)
        pcm = audio.detach().cpu().numpy().reshape(-1).astype(np.float32)
        wav = out_dir / f"{r['id']}.wav"
        scipy.io.wavfile.write(wav, model.sample_rate, pcm)
        f.write(
            json.dumps(
                {
                    **r,
                    "wav": wav.name,
                    "dtype": "torch_fp32",
                    "unit": "cpu",
                    "samples": int(pcm.size),
                    "duration_s": round(pcm.size / model.sample_rate, 3),
                    "peak": round(float(np.abs(pcm).max()) if pcm.size else 0.0, 4),
                    "rms": round(float(np.sqrt((pcm**2).mean())) if pcm.size else 0.0, 5),
                    "wall_s": round(time.monotonic() - t1, 3),
                    "chunks": [],
                    "no_eos": False,
                    "kv_capped": False,
                }
            )
            + "\n"
        )
        f.flush()
        if k % 20 == 0:
            print(f"[torch] {k}/{len(rows)}  {time.monotonic() - t0:.0f}s", flush=True)
    f.close()
    print(f"[torch] done, {time.monotonic() - t0:.0f}s")


if __name__ == "__main__":
    main()
